name: wikichen is
description: wikichen plays here.
url: http://wikichen.is
author:
  name: Jonathan E. Chen
  email: hello@wikichen.is

highlighter: rouge

permalink: /sharing/:title/

collections:
  projects:
    output: true
  stories:
    output: true
  books:
    output: true

defaults:
  - scope:
      path: "" # select all filesd
    values:
      layout: "post"

cdn_baseurl: http://cloud.wikichen.is
cdn_url: http://cloud.wikichen.is/serving

enable_disqus: false

exclude: ['Gemfile',
          'gulpfile.js',
          'node_modules',
          'package.json',
          'Rakefile',
          's3_website.yml',
          'README.md',
          'LICENSE']
