name: wikichen
description: wikichen is a blog
url: http://wikichen.is
author:
  name: Jonathan E. Chen
  email: hello@wikichen.is

markdown: kramdown
highlighter: rouge

permalink: /:title/

enable_disqus: false

exclude: ['Gemfile',
          'gulpfile.js',
          'node_modules',
          'package.json',
          's3_website.yml',
          'README.md',
          'LICENSE']
