name: WIKICHEN
description: wikichen's personal zine on the web
url: http://wikichen.is
author:
  name: Jonathan E. Chen
  email: hello@wikichen.is

highlighter: rouge

permalink: /:title/

defaults:
  - scope:
      path: "" # select all files
    values:
      layout: "post"

cdn_baseurl: http://cloud.wikichen.is
cdn_url: http://cloud.wikichen.is/serving

enable_disqus: false

exclude: ['Gemfile',
          'gulpfile.js',
          'node_modules',
          'package.json',
          'Rakefile',
          's3_website.yml',
          'README.md',
          'LICENSE']
